# Generated by Django 5.1.2 on 2024-10-08 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagination_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="user_id",
        ),
    ]
